# Generated by Django 2.2.4 on 2019-08-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=200)),
                ('phone_number', models.IntegerField(verbose_name=20)),
            ],
        ),
        migrations.CreateModel(
            name='vaccine_compare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100)),
                ('vaccine_time', models.IntegerField(verbose_name=50)),
                ('short_name_vaccine', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('is_child', models.BooleanField(default=False)),
            ],
        ),
    ]
